version: '3.8'
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://backend-dev:3000
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    command: pnpm dev --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SUPABASE_URL=${VITE_SUPABASE_URL}
      - SUPABASE_KEY=${VITE_SUPABASE_ANON_KEY}
    command: pnpm dev
    restart: unless-stopped