version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=https://pekvqloryuqpccjuvrdz.supabase.co
        - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBla3ZxbG9yeXVxcGNjanV2cmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDY4MTQsImV4cCI6MjA2MTY4MjgxNH0._hoUFAVlaJcrF14EHdbzDr7bBwik9Rl9_b8Zbj3qUgQ
        - VITE_BACKEND_URL=http://backend:3000
    ports:
      - "4173:4173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=https://pekvqloryuqpccjuvrdz.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBla3ZxbG9yeXVxcGNjanV2cmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDY4MTQsImV4cCI6MjA2MTY4MjgxNH0._hoUFAVlaJcrF14EHdbzDr7bBwik9Rl9_b8Zbj3qUgQ
    restart: unless-stopped