CREATE TABLE
  users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
  );

CREATE TABLE
  folders (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_folder_id INT REFERENCES folders (id) ON DELETE CASCADE,
    user_id INT REFERENCES users (id) ON DELETE CASCADE
  );

CREATE TABLE
  files (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    folder_id INT REFERENCES folders (id) ON DELETE CASCADE,
    user_id INT REFERENCES users (id) ON DELETE CASCADE
  );

CREATE TABLE
  activity_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    action VARCHAR(255) NOT NULL,
    details TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

ALTER TABLE files
ADD COLUMN is_trashed BOOLEAN DEFAULT false;

ALTER TABLE files
ADD COLUMN size BIGINT NOT NULL DEFAULT 0;

CREATE TABLE
  tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE
  file_tags (
    file_id INTEGER REFERENCES files (id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (file_id, tag_id)
  );